const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.NinePatch,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Flowchart,
		C3.Plugins.Keyboard,
		C3.Plugins.Dictionary,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Flowchart.Acts.StartFlowchart,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Text.Cnds.IsRunningTypewriterText,
		C3.Plugins.Text.Acts.TypewriterFinish,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Flowchart.Cnds.HasOutput,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Flowchart.Exps.OutputValue,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Flowchart.Acts.GotoNextFlowchartNode,
		C3.Plugins.NinePatch.Cnds.CompareOpacity,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.NinePatch.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.int,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.Text.Cnds.OnTypewriterTextFinished,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Flowchart.Acts.ResetFlowchart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Dictionary.Acts.SetKey,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.Height
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{DialogueBox: 0},
	{Background: 0},
	{Fader: 0},
	{Dialogue: 0},
	{Flow: 0},
	{actorID: 0},
	{onStage: 0},
	{Actor: 0},
	{name: 0},
	{CharPosRef: 0},
	{Keyboard: 0},
	{DropShadow: 0},
	{id: 0},
	{ChoiceRef: 0},
	{selection: 0},
	{SelectionBox: 0},
	{DictBools: 0},
	{COLOR0: 0},
	{COLOR1: 0},
	{FADE_NORMAL: 0},
	{FADE_FAST: 0},
	{nextNode: 0},
	{dialogueText: 0},
	{shadowText: 0},
	{side: 0}
];

self.InstanceType = {
	DialogueBox: class extends self.IWorldInstance {},
	Background: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	Dialogue: class extends self.ITextInstance {},
	Flow: class extends self.IInstance {},
	Actor: class extends self.ISpriteInstance {},
	CharPosRef: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DropShadow: class extends self.ITextInstance {},
	ChoiceRef: class extends self.ISpriteInstance {},
	SelectionBox: class extends self.IWorldInstance {},
	DictBools: class extends self.IDictionaryInstance {}
}